version: '3.4'
services:
   jupyter:
      build: 
         context: ./az_en_jupyter2_mappam
         network: host
      container_name: jupyter
      restart: always
      user: '0'
      ports:
         - '8888:8888'
      volumes:
         - ./az_en_jupyter2_mappam:/home/jovyan/work